
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button _newTab;
	private global::Gtk.Button _goBack;
	private global::Gtk.Button _goForward;
	private global::Gtk.Button _reload;
	private global::Gtk.Button _stop;
	private global::Gtk.Button _home;
	private global::Gtk.Entry _address;
	private global::Gtk.Notebook _tabs;
	private global::Gtk.Label label1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 1;
		this.vbox1.BorderWidth = ((uint)(1));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this._newTab = new global::Gtk.Button ();
		this._newTab.CanFocus = true;
		this._newTab.Name = "_newTab";
		this._newTab.UseUnderline = true;
		this._newTab.FocusOnClick = false;
		this._newTab.Relief = ((global::Gtk.ReliefStyle)(2));
		// Container child _newTab.Gtk.Container+ContainerChild
		global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w2 = new global::Gtk.HBox ();
		w2.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w3 = new global::Gtk.Image ();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.SmallToolbar);
		w2.Add (w3);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w2.Add (w5);
		w1.Add (w2);
		this._newTab.Add (w1);
		this.hbox1.Add (this._newTab);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._newTab]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._goBack = new global::Gtk.Button ();
		this._goBack.CanFocus = true;
		this._goBack.Name = "_goBack";
		this._goBack.UseUnderline = true;
		this._goBack.FocusOnClick = false;
		this._goBack.Relief = ((global::Gtk.ReliefStyle)(2));
		// Container child _goBack.Gtk.Container+ContainerChild
		global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w11 = new global::Gtk.HBox ();
		w11.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w12 = new global::Gtk.Image ();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.SmallToolbar);
		w11.Add (w12);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w14 = new global::Gtk.Label ();
		w11.Add (w14);
		w10.Add (w11);
		this._goBack.Add (w10);
		this.hbox1.Add (this._goBack);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._goBack]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._goForward = new global::Gtk.Button ();
		this._goForward.CanFocus = true;
		this._goForward.Name = "_goForward";
		this._goForward.UseUnderline = true;
		this._goForward.FocusOnClick = false;
		this._goForward.Relief = ((global::Gtk.ReliefStyle)(2));
		// Container child _goForward.Gtk.Container+ContainerChild
		global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w20 = new global::Gtk.HBox ();
		w20.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w21 = new global::Gtk.Image ();
		w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.SmallToolbar);
		w20.Add (w21);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w23 = new global::Gtk.Label ();
		w20.Add (w23);
		w19.Add (w20);
		this._goForward.Add (w19);
		this.hbox1.Add (this._goForward);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._goForward]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._reload = new global::Gtk.Button ();
		this._reload.CanFocus = true;
		this._reload.Name = "_reload";
		this._reload.UseUnderline = true;
		this._reload.FocusOnClick = false;
		this._reload.Relief = ((global::Gtk.ReliefStyle)(2));
		// Container child _reload.Gtk.Container+ContainerChild
		global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w29 = new global::Gtk.HBox ();
		w29.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w30 = new global::Gtk.Image ();
		w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.SmallToolbar);
		w29.Add (w30);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w32 = new global::Gtk.Label ();
		w29.Add (w32);
		w28.Add (w29);
		this._reload.Add (w28);
		this.hbox1.Add (this._reload);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._reload]));
		w36.Position = 3;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._stop = new global::Gtk.Button ();
		this._stop.CanFocus = true;
		this._stop.Name = "_stop";
		this._stop.UseUnderline = true;
		this._stop.FocusOnClick = false;
		this._stop.Relief = ((global::Gtk.ReliefStyle)(2));
		// Container child _stop.Gtk.Container+ContainerChild
		global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w38 = new global::Gtk.HBox ();
		w38.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w39 = new global::Gtk.Image ();
		w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.SmallToolbar);
		w38.Add (w39);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w41 = new global::Gtk.Label ();
		w38.Add (w41);
		w37.Add (w38);
		this._stop.Add (w37);
		this.hbox1.Add (this._stop);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._stop]));
		w45.Position = 4;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._home = new global::Gtk.Button ();
		this._home.CanFocus = true;
		this._home.Name = "_home";
		this._home.UseUnderline = true;
		this._home.FocusOnClick = false;
		this._home.Relief = ((global::Gtk.ReliefStyle)(2));
		// Container child _home.Gtk.Container+ContainerChild
		global::Gtk.Alignment w46 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w47 = new global::Gtk.HBox ();
		w47.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w48 = new global::Gtk.Image ();
		w48.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-home", global::Gtk.IconSize.Menu);
		w47.Add (w48);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w50 = new global::Gtk.Label ();
		w47.Add (w50);
		w46.Add (w47);
		this._home.Add (w46);
		this.hbox1.Add (this._home);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._home]));
		w54.Position = 5;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._address = new global::Gtk.Entry ();
		this._address.CanFocus = true;
		this._address.Name = "_address";
		this._address.IsEditable = true;
		this._address.InvisibleChar = '•';
		this.hbox1.Add (this._address);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._address]));
		w55.Position = 6;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this._tabs = new global::Gtk.Notebook ();
		this._tabs.CanFocus = true;
		this._tabs.Name = "_tabs";
		this._tabs.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w57 = new global::Gtk.Label ();
		w57.Visible = true;
		this._tabs.Add (w57);
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("New Tab");
		this._tabs.SetTabLabel (w57, this.label1);
		this.label1.ShowAll ();
		this.vbox1.Add (this._tabs);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._tabs]));
		w58.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 708;
		this.DefaultHeight = 453;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this._newTab.Clicked += new global::System.EventHandler (this.NewTab);
	}
}
