//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3239.1705.gf6d6dfc";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1705;
        public const string CEF_COMMIT_HASH = "f6d6dfc8591fe6d014c3b97fa8eef695cebfa40e";
        
        public const int CHROME_VERSION_MAJOR = 63;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3239;
        public const int CHROME_VERSION_PATCH = 109;
        
        public const string CEF_API_HASH_UNIVERSAL = "8b2f1ea4d6585813e6919ace8b3d10ebeb7ceaa0";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "b9cb6b3e28978a42e2b6dc4a5c9adc7091bf7946";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "b8706ecf7ab96880a80f58cb8100df1e477a6bbc";
        public const string CEF_API_HASH_PLATFORM_LINUX = "49fd2b5c8416ae02dbfdd3c729ca4f0fa080de4c";
    }
}
